const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    REDUCE_ITEM_QUANTITY: 'REDUCE_ITEM_QUANTITY',
};

export default CartActionTypes;